In [165]:
import numpy as np
import pandas as pd

In [166]:
df = pd.read_csv('Players report.csv')

In [167]:
df.head()

Name  Matches   Inns    Runs  Highest score      SR  100s  \
0          MS Dhoni    332.0  296.0  6821.0           84.0  134.90   0.0   
1         Moeen Ali    168.0  159.0  3549.0          121.0  140.27   2.0   
2           KM Asif     15.0    3.0     1.0            1.0   33.33   0.0   
3  Jason Behrendoff     79.0   17.0    87.0           26.0  108.74   0.0   
4     Bhagath varma      NaN    NaN     NaN            NaN     NaN   NaN   

    50s     4s     6s   Balls   Econ   4w   wkts        Status  
0  27.0  467.0  302.0    12.0  12.50  0.0    0.0      selected  
1  19.0  350.0  156.0  2333.0   7.71  1.0  111.0      selected  
2   0.0    0.0    0.0   282.0   8.00  0.0   17.0  not selected  
3   0.0    7.0    1.0  1670.0   7.20  2.0   90.0  not selected  
4   NaN    NaN    NaN     NaN    NaN  NaN    NaN           NaN

In [168]:
X = df[['Runs', 'Highest score', 'SR']]
y = df['Status']

In [169]:
X.dropna(inplace=True)

<ipython-input-169-32f8c2353909>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.dropna(inplace=True)


In [170]:
X.isnull().sum()

Runs             0
Highest score    0
SR               0
dtype: int64

In [172]:
y.dropna(inplace=True)

In [173]:
from sklearn.preprocessing import OneHotEncoder

In [174]:
encoder = OneHotEncoder()

In [175]:
X = encoder.fit_transform(X)

In [176]:
X

<25x73 sparse matrix of type '<class 'numpy.float64'>'
	with 75 stored elements in Compressed Sparse Row format>

In [177]:
type(X)

scipy.sparse.csr.csr_matrix

In [178]:
X = X.toarray()

In [180]:
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [181]:
y.shape

(25,)

In [183]:
y = np.array(y)

In [187]:
y = y.reshape(-1, 1)

In [188]:
y.ndim

2

In [189]:
from sklearn.model_selection import train_test_split

In [190]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [191]:
X_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [192]:
from sklearn.svm import LinearSVC

In [193]:
lr = LinearSVC()

In [194]:
lr.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LinearSVC()

In [195]:
predictions = lr.predict(X_test)

In [196]:
predictions

array(['selected', 'selected', 'selected', 'selected', 'selected',
       'selected', 'selected', 'selected'], dtype=object)

In [211]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [213]:
confusion_matrix(predictions, y_test)

array([[8]], dtype=int64)

In [214]:
accuracy_score(y_test, predictions)

1.0

In [216]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

    selected       1.00      1.00      1.00         8

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

