In [67]:
import random
import numpy as np
import pandas as pd

In [68]:
df = pd.read_csv('Players report.csv')

In [69]:
df.head()

Name  Matches   Inns    Runs  Highest score      SR  100s  \
0          MS Dhoni    332.0  296.0  6821.0           84.0  134.90   0.0   
1         Moeen Ali    168.0  159.0  3549.0          121.0  140.27   2.0   
2           KM Asif     15.0    3.0     1.0            1.0   33.33   0.0   
3  Jason Behrendoff     79.0   17.0    87.0           26.0  108.74   0.0   
4     Bhagath varma      NaN    NaN     NaN            NaN     NaN   NaN   

    50s     4s     6s   Balls   Econ   4w   wkts        Status  
0  27.0  467.0  302.0    12.0  12.50  0.0    0.0      selected  
1  19.0  350.0  156.0  2333.0   7.71  1.0  111.0      selected  
2   0.0    0.0    0.0   282.0   8.00  0.0   17.0  not selected  
3   0.0    7.0    1.0  1670.0   7.20  2.0   90.0  not selected  
4   NaN    NaN    NaN     NaN    NaN  NaN    NaN           NaN

In [70]:
X = df[['Runs', 'Highest score', 'SR']]
y = df['Status']

In [73]:
X.shape

(29, 3)

In [74]:
X.isnull().sum()

Runs             4
Highest score    4
SR               4
dtype: int64

In [75]:
y.isnull().sum()

4

In [76]:
X.dropna(inplace=True)
y.dropna(inplace=True)

<ipython-input-76-984dbda9642f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.dropna(inplace=True)


In [78]:
from sklearn.feature_selection import SelectKBest, f_classif

In [79]:
best = SelectKBest(score_func=f_classif, k='all')

In [80]:
print(best)

SelectKBest(k='all')


In [82]:
a = best.fit(X, y)

In [83]:
print(a)

SelectKBest(k='all')


In [84]:
feature_x = a.transform(X)

In [85]:
print(feature_x)

[[6.8210e+03 8.4000e+01 1.3490e+02]
 [3.5490e+03 1.2100e+02 1.4027e+02]
 [1.0000e+00 1.0000e+00 3.3330e+01]
 [8.7000e+01 2.6000e+01 1.0874e+02]
 [6.3370e+03 1.1200e+02 1.2000e+02]
 [2.6500e+02 5.5000e+01 1.2500e+02]
 [1.0940e+03 5.5000e+01 1.3325e+02]
 [5.9660e+03 1.1900e+02 1.2791e+02]
 [1.1510e+03 8.2000e+01 1.2831e+02]
 [5.9400e+02 6.0000e+01 1.5924e+02]
 [2.6120e+03 5.0000e+01 1.2710e+02]
 [7.0200e+02 7.8000e+01 1.2535e+02]
 [1.4000e+01 4.0000e+00 5.8330e+01]
 [8.5560e+03 1.2600e+02 1.3771e+02]
 [5.2550e+03 1.0000e+02 1.2355e+02]
 [1.1270e+03 4.5000e+01 1.2748e+02]
 [1.3670e+03 6.7000e+01 1.2704e+02]
 [1.7800e+02 2.2000e+01 1.1558e+02]
 [2.3000e+01 1.2000e+01 8.8460e+01]
 [6.8610e+03 9.2000e+01 1.3288e+02]
 [9.7970e+03 1.1300e+02 1.3407e+02]
 [9.1600e+03 1.3300e+02 1.5021e+02]
 [6.2500e+02 9.2000e+01 1.8768e+02]
 [7.3000e+02 7.6000e+01 1.0610e+02]
 [5.1730e+03 1.2900e+02 1.3992e+02]]


In [88]:
type(feature_x)

numpy.ndarray

In [90]:
from sklearn.preprocessing import LabelEncoder

In [91]:
encoder = LabelEncoder()

In [92]:
y_encoder = encoder.fit(y)

In [93]:
print(y_encoder)

LabelEncoder()


In [94]:
feature_y = y_encoder.transform(y)

In [95]:
from sklearn.model_selection import train_test_split

In [96]:
X_train, X_test, y_train, y_test = train_test_split(feature_x, feature_y, test_size=0.3, random_state=42)

In [98]:
y_train

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])

In [99]:
from sklearn.ensemble import RandomForestClassifier

In [100]:
rf = RandomForestClassifier()

In [101]:
clf = rf.fit(X_train, y_train)

In [102]:
predictions = clf.predict(X_test)

In [103]:
print(predictions)

[1 1 1 1 1 1 1 1]


In [105]:
y_encoder.inverse_transform(predictions)

array(['selected', 'selected', 'selected', 'selected', 'selected',
       'selected', 'selected', 'selected'], dtype=object)

In [106]:
query = 2000, 100, 140

res = clf.predict([query])

In [107]:
y_encoder.inverse_transform(res)

array(['selected'], dtype=object)

In [108]:
query1 = 500, 30, 90

res = clf.predict([query1])

In [109]:
y_encoder.inverse_transform(res)

array(['not selected'], dtype=object)

In [110]:
from joblib import dump, load

In [111]:
dump(clf, 'trained_fantacy_model.sav')

['trained_fantacy_model.sav']

In [112]:
model = load('trained_fantacy_model.sav')

In [119]:
res = model.predict([[2000, 35, 89.5]])

In [121]:
print(y_encoder.inverse_transform(res))

['not selected']
